on:
  push:
  pull_request:

jobs:
  tsc:
    name: tsc
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install node v18
      uses: actions/setup-node@v1
      with:
        node-version: 18
    - name: yarn install
      run: yarn install
    - name: install types for node
      run: yarn add @types/node --dev
    - name: tsc
      uses: icrawl/action-tsc@v1
